apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deployapp
  namespace: default
spec:
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployapp
