version: '3.8'

services:
  mongo:
    container_name: joktec-mongo
    image: mongo:7.0.2
    ports:
      - '27017:27017'
    volumes:
      - .docker/mongo/data:/data/db
      - .docker/mongo/backup:/data/backup
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - joktec-network
    restart: always
    logging:
      options:
        max-size: '100k'
    healthcheck:
      test: [ "CMD", "mongo", "--quiet", "127.0.0.1/test", "--eval", "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'" ]
      start_period: 40s
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    container_name: joktec-postgres
    image: postgres:15.2
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - joktec-network
    restart: always
    logging:
      options:
        max-size: '100k'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql:
    container_name: joktec-mysql
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - .docker/mysql/data:/var/lib/mysql
      - .docker/mysql/backup:/var/lib/backup
      - .docker/mysql/provision/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    networks:
      - joktec-network
    restart: always
    logging:
      options:
        max-size: '100k'
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 30s
      timeout: 10s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sort_buffer_size=512K --sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"

  mssql:
    container_name: joktec-mssql
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - '1433:1433'
    volumes:
      - .docker/mssql/data:/var/opt/mssql
    cap_add:
      - SYS_PTRACE
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=reallyStrongPwd123
    user: mssql:10001   # Set the non-root user explicitly
    networks:
      - joktec-network
    restart: always
    logging:
      options:
        max-size: '100k'

  cassandra:
    container_name: joktec-cassandra
    image: cassandra:5.0
    ports:
      - '9042:9042'
    volumes:
      - .docker/cassandra/data:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: cloudinfra
      CASSANDRA_USER: root
      CASSANDRA_PASSWORD: root
    networks:
      - joktec-network
    restart: always
    logging:
      options:
        max-size: '100k'

  redis:
    container_name: joktec-redis
    image: redis:6.2.0
    ports:
      - '6379:6379'
    volumes:
      - .docker/redis/data:/data
      - .docker/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: root
    networks:
      - joktec-network
    command: redis-server --requirepass root --appendonly yes
    restart: always
    logging:
      options:
        max-size: '100k'
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    container_name: joktec-rabbitmq
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - .docker/rabbitmq/data/:/var/lib/rabbitmq/
      - .docker/rabbitmq/log/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - joktec-network
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    container_name: joktec-minio
    image: minio/minio
    volumes:
      - .docker/minio/data:/data
    ports:
      - "9000:9000"
      - '9090:9090'
    environment:
      MINIO_ACCESS_KEY: accesskey
      MINIO_SECRET_KEY: secretkey
    restart: always
    logging:
      options:
        max-size: '100k'
    networks:
      - joktec-network
    command: server /data --console-address ":9090"
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    container_name: joktec-grafana
    image: grafana/grafana:9.5.2
    ports:
      - "3033:3000"
    volumes:
      - .docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - .docker/grafana/data:/var/lib/grafana
    restart: always
    networks:
      - joktec-network

  elasticsearch:
    container_name: joktec-elastic
    image: bitnami/elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - .docker/elk/elastic/data:/bitnami/elasticsearch/data
      - docker/elk/elastic/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - ELASTICSEARCH_HEAP_SIZE=256m
      - ELASTICSEARCH_NODE_NAME=elasticsearch
      - ELASTICSEARCH_CLUSTER_NAME=es-docker-cluster
      - ELASTICSEARCH_SKIP_TRANSPORT_TLS=false
      - ELASTICSEARCH_LOCK_ALL_MEMORY=true
    restart: always
    logging:
      options:
        max-size: '100k'
    networks:
      - joktec-network

  logstash:
    container_name: joktec-logstash
    image: bitnami/logstash:latest
    ports:
      - '5010:5010'
      - '5044:5044'
      - '9600:9600'
    volumes:
      - docker/elk/logstash/logstash.conf:/opt/bitnami/logstash/pipeline/logstash.conf
    environment:
      - LOGSTASH_HEAP_SIZE=256m
      - LOGSTASH_ELASTICSEARCH_HOST=elasticsearch
      - LOGSTASH_ELASTICSEARCH_PORT_NUMBER=9200
    depends_on:
      - elasticsearch
    restart: always
    logging:
      options:
        max-size: '100k'
    networks:
      - joktec-network

  kibana:
    container_name: joktec-kibana
    image: bitnami/kibana:latest
    ports:
      - "5601:5601"
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch
      - KIBANA_ELASTICSEARCH_PORT_NUMBER=9200
    depends_on:
      - elasticsearch
    restart: always
    logging:
      options:
        max-size: '100k'
    networks:
      - joktec-network

# Docker Networks
networks:
  joktec-network:
    name: joktec-network
    driver: bridge

# Docker Volumes
volumes:
  .docker:
    driver: local
