apiVersion: v1
kind: Pod
metadata:
  name: tools
  labels:
    app: tools
spec:
  containers:
  - name: tools
    image: ichte/coretools
    resources: {}
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo 'coretools running'; sleep 10;done"]
#    livenessProbe:
#      httpGet:
#        path: /healthycheck
#        port: 8085
#      initialDelaySeconds: 10
#      periodSeconds: 10
